name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Ensures submodules are cloned and initialized

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format valgrind bc
          version: 1.0

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run documentation check
        uses: ./.github/actions/documentation

      - name: Install Conan
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install conan

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc g++ libmicrohttpd-dev

      - name: Clone prometheus-client-c repository
        run: |
          git clone https://github.com/digitalocean/prometheus-client-c.git
          cd prometheus-client-c
          git submodule update --init --recursive  # Ensure submodules are initialized

      - name: Fix incompatible function pointer in promhttp.c
        run: |
          cd prometheus-client-c
          sed -i 's/&promhttp_handler/(MHD_AccessHandlerCallback)promhttp_handler/' promhttp/src/promhttp.c

      - name: Build prom library
        run: |
          mkdir -p prometheus-client-c/buildprom
          cd prometheus-client-c/buildprom
          cmake ../prom
          make
          sudo make install

      - name: Build promhttp library
        run: |
          mkdir -p prometheus-client-c/buildpromhttp
          cd prometheus-client-c/buildpromhttp
          cmake ../promhttp
          make
          sudo make install

      - name: Create default Conan profile
        run: |
          conan profile detect
      
      - name: Modify default Conan profile
        run: |
          echo "compiler.libcxx=libstdc++11" >> /home/runner/.conan2/profiles/default
      
      - name: Build project
        run: |
          mkdir -p build
          cd build
          conan install .. -of .
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          make
      
      - name: Run tests and coverage
        uses: ./.github/actions/coverage_and_test
